kubeconfig: "~/.kube/config"

# venv + paths
venv_path: ".venv"
collections_path: "./collections"
rendered_playbook_path: "./build/generated-playbook.yaml"

install_gitops_operator: true
gitops_channel: gitops-1.17
gitops_source: redhat-operators
gitops_source_namespace: openshift-marketplace
gitops_approval: Automatic

# Namespaces
argocd_namespace: "openshift-gitops"
app_a_namespace: "app-a"
apps_namespaces: 
  - "app-b"
  - "app-c"
target_namespace: "my-apps"

# Git host + repo creds
create_workload_github_secret: false 
github_host: "github.com"
github_repo_url: "https://github.com/rh-fran6/htcdemo.git"
github_username: "rh-fran6"

# External Secret Operator Backhaul to AWS SM
create_aws_sm_secret: true

# Argo CD RBAC (parameterized)
rbac_scopes: "[groups]"
rbac_default_policy: "role:readonly"
rbac_groups:
  - { name: "admin-team", role: "admin" }
  - { name: "devops-team", role: "devops" }
  - { name: "app-a-team", role: "app-a" }
  - { name: "noc-team",   role: "noc" }
rbac_roles:
  - name: "devops"
    permissions:
      - { resource: "applications", action: "*",     object: "platform/*" }
      - { resource: "projects",     action: "get",   object: "platform" }
      - { resource: "clusters",     action: "*",     object: "*" }
      - { resource: "repositories", action: "*",     object: "*" }
      - { resource: "logs",         action: "get",   object: "*" }
      - { resource: "exec",         action: "create",object: "*" }
      - { resource: "certificates", action: "*",     object: "*" }
      - { resource: "accounts",     action: "get",   object: "*" }
      - { resource: "gpgkeys",      action: "*",     object: "*" }
  - name: "app-a"
    permissions:
      - { resource: "applications", action: "get",  object: "app-a/*" }
      - { resource: "applications", action: "sync", object: "app-a/*" }
      - { resource: "projects",     action: "get",  object: "app-a" }
  - name: "noc"
    permissions:
      - { resource: "applications", action: "get",  object: "apps/*" }
      - { resource: "projects",     action: "get",  object: "apps" }

bootstrap_enabled: true
bootstrap_app_name: "bootstrap"
bootstrap_repo_url: "{{ github_repo_url }}" 
bootstrap_target_revision: "main"
bootstrap_path: "bootstrap"                  
bootstrap_project: "platform"        





